FROM eaps-docker-coldfusion.bintray.io/cf/coldfusion:latest-2018
# COPY mysql-connector-java-commercial-5.1.25-bin.jar /opt/coldfusion/cfusion/lib
COPY ../database/mysql-connector-java-5.1.18.bundle.jar /opt/coldfusion/cfusion/lib
